#!/bin/bash
set -euo pipefail

# Load config
source "$(dirname "$0")/.env"

full=$(pwd)
base=$CODE_PATH
if [[ "$full" == "$base"* ]]; then
    prep="cd $full; "
else
    prep=""
fi
ssh -t -p 2222 localhost "$prep GH_TOKEN=$(op plugin run -- gh auth token) ~/.local/bin/claude --dangerously-skip-permissions"
