#!/bin/sh
# Entrypoint runs as root: sets up SSH, then drops to the non-root user.

if [ ! -f /etc/ssh/ssh_host_ed25519_key ]; then
  cp -r /etc/ssh.original/. /etc/ssh/
  ssh-keygen -A
fi
cp /etc/ssh.original/sshd_config /etc/ssh/sshd_config

# Fix ownership on named volumes (created as root by Docker)
USER_HOME="$(eval echo ~"$APP_USER")"
for dir in "$USER_HOME/.local/share/mise" "$USER_HOME/.cache"; do
  [ -d "$dir" ] && chown -R "$APP_USER:$APP_USER" "$dir" 2>/dev/null || true
done

# Copy .claude.json from the directory-mounted staging area into the real path.
# This avoids Docker single-file bind mount corruption caused by atomic writes.
STAGED_CLAUDE_JSON="$USER_HOME/.claude-mount-stage/.claude.json"
if [ -f "$STAGED_CLAUDE_JSON" ]; then
  cp "$STAGED_CLAUDE_JSON" "$USER_HOME/.claude.json"
  chown "$APP_USER:$APP_USER" "$USER_HOME/.claude.json"
fi

# Iron-proxy integration (enabled by modules/iron-proxy.yml setting IRON_PROXY).
# The real secrets live only in the proxy; here we (1) trust the proxy CA so
# MITM'd TLS verifies, and (2) capture placeholder tokens + CA paths into a file
# that every shell sources (see files/20-iron-proxy.sh), so they stay available
# to all sessions and background processes — not just the SSH session.
if [ -n "${IRON_PROXY:-}" ]; then
  if [ -f /usr/local/share/ca-certificates/iron-proxy-ca.crt ]; then
    update-ca-certificates >/dev/null 2>&1 || true
  fi

  mkdir -p /etc/claude-docker
  cat > /etc/claude-docker/iron-proxy.env <<'IRONENV'
# Generated by entrypoint.sh — do not edit. Sourced by ~/.zshrc.d/20-iron-proxy.sh.
# Placeholder GitHub token; iron-proxy swaps it for the real one for api.github.com.
export GH_TOKEN="proxy-gh-token"
# Trust the proxy CA in tools that don't read the system store.
export NODE_EXTRA_CA_CERTS="/usr/local/share/ca-certificates/iron-proxy-ca.crt"
export SSL_CERT_FILE="/etc/ssl/certs/ca-certificates.crt"
export REQUESTS_CA_BUNDLE="/etc/ssl/certs/ca-certificates.crt"
IRONENV
  chmod 644 /etc/claude-docker/iron-proxy.env
fi

# Run user-provided init scripts (compose overlays bind-mount into this dir)
for f in /etc/claude-docker/init.d/*.sh; do
  [ -f "$f" ] && . "$f"
done

exec /usr/sbin/sshd -D
